### ISSUE TITLE
some question about feature enable

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-anycode#46]
hi, I install the anycode in my desktop vscode
and python and c# are both installed too.

and there is some case I can't understand: should I enable those feature explicitly？
like:
``` 
    "[csharp][c][cpp][python]": {
        "anycode.language.features": {
            "completions": true,
            "definitions": true,
            "references": true,
            "workspaceSymbols": true,
            "highlights": false,
            "outline": false,
            "diagnostics": false
        }
    },
```
1. by default.
nothhing while press F12

![image](https://user-images.githubusercontent.com/1876302/177586127-8d7f9717-25b9-40ac-af76-116f293eaf0f.png)

2. ENABLE THE SETTING  explicitly
press F12 and we could find something.
![image](https://user-images.githubusercontent.com/1876302/177586093-ba8daa52-d021-45b7-ad1b-bebf09410e4d.png)

I notice that the default setting of anycode are:
```
        "anycode.language.features": {
            "completions": true,
            "definitions": true,
            "references": true,
            "workspaceSymbols": true,
            "highlights": false,
            "outline": false,
            "diagnostics": false
        }
```

Is it means that we should enable then explicitly

**Comment by jrieken** [comment]
> hi, I install the anycode in my desktop vscode
and python and c# are both installed too.

anycode language extensions disable themselves when some "real" language extensions are around, e.g `anycode-python` is suppressed by ["ms-python.python"](https://github.com/microsoft/vscode-anycode/blob/4503b7be951f3b6f3bb4afcd0a3455770e673cdc/anycode-python/package.json#L40) and so on. This can be overruled when the user explicitly configures the language to be enabled. 

We do that because the "real" language extensions are usually of higher quality and anycode shouldn't pollute good results with its lower quality results

**Comment by heartacker** [comment]
thanks for your reply， and I think we can close the issue now https://github.com/microsoft/vscode-anycode/issues/21

>anycode language extensions disable themselves when some "real" language extensions are around

and also， could it be described to readme and/or wiki
